### ISSUE TITLE
Property List error: Cannot parse a NULL or zero-length data

### ISSUE THREAD

**Issue by eramdam** [dangh/force-rgb.fish#1]
I'm getting the following errors when running the script

```
Fixing /Library/Preferences/com.apple.windowserver.displays.plist
/var/folders/c9/z8mfllrs7n1gvpddbd9w6fx40000gn/T/tmp.ES7uutmQ: Property List error: Cannot parse a NULL or zero-length data / JSON error: Unable to parse empty data.
Fixing /Users/damien/Library/Preferences/ByHost/com.apple.windowserver.displays.31A65C41-ACD4-5833-B863-11BCFF6D01CD.plist


/var/folders/c9/z8mfllrs7n1gvpddbd9w6fx40000gn/T/tmp.ZVtFgaRJ: Property List error: Cannot parse a NULL or zero-length data / JSON error: Unable to parse empty data.
Done. Log out BEFORE reboot your mac to apply changes.
```

Then I end up with empty plist files. I attached my original plist files 

[original-plist.zip](https://github.com/dangh/force-rgb.fish/files/9388820/original-plist.zip)

Running macOS 12.5.1 and fish 3.5.1

**Comment by dangh** [comment]
Hi @eramdam, thanks for reporting. I have added support for macOS 12. The plist structure is a bit different on macOS 13 :)

The script will be dryrun by default, so we don't mess up the plist files. To apply changes, you need to run it as

```sh
yes | force-rgb
```

**Comment by eramdam** [comment]
That fixed it! Thanks for the quick turn around 😁
